<?php

/**
 * @file
 * nexteuropa_newsroom.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function nexteuropa_newsroom_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => "1");
  }
  if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
    return array("version" => "2");
  }
}
