<?php

/**
 * @file
 * nexteuropa_newsroom_entities.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function nexteuropa_newsroom_entities_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function nexteuropa_newsroom_entities_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function nexteuropa_newsroom_entities_node_info() {
  $items = array(
    'newsroom_item' => array(
      'name' => t('Newsroom Item'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'newsroom_selection' => array(
      'name' => t('Newsroom Selection'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'newsroom_newsletter_issue' => array(
      'name' => t('Newsroom newsletter issue'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
